config/routes.rb
Zaklady::Application.routes.draw do
  
  root :to => 'zaklads#index'

  resources :obstawienies

  resources :zaklads

 

  get "zaklady/nowy"
  post "zaklady/nowy"

  get "zaklady/wynik"
  post "zaklady/wynik"

end

app/models/zaklad.rb
class Zaklad < ActiveRecord::Base
  attr_accessible :data, :gosc, :gospodarz, :k1, :k2, :k3, :event_id
  belongs_to :event
  has_many :obstawienies, :class_name => 'Obstawienie'
end

app/controllers/zaklads_controller.rb
class ZakladsController < ApplicationController
  # GET /zaklads
  # GET /zaklads.json
  def index
    @zaklads = Zaklad.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zaklads }
    end
  end

  # GET /zaklads/1
  # GET /zaklads/1.json
  def show
    @zaklad = Zaklad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zaklad }
    end
  end

  # GET /zaklads/new
  # GET /zaklads/new.json
  def new
    @zaklad = Zaklad.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zaklad }
    end
  end

  # GET /zaklads/1/edit
  def edit
    @zaklad = Zaklad.find(params[:id])
  end

  # POST /zaklads
  # POST /zaklads.json
  def create
    @zaklad = Zaklad.new(params[:zaklad])

    respond_to do |format|
      if @zaklad.save
        format.html { redirect_to @zaklad, notice: 'Zaklad was successfully created.' }
        format.json { render json: @zaklad, status: :created, location: @zaklad }
      else
        format.html { render action: "new" }
        format.json { render json: @zaklad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zaklads/1
  # PUT /zaklads/1.json
  def update
    @zaklad = Zaklad.find(params[:id])

    respond_to do |format|
      if @zaklad.update_attributes(params[:zaklad])
        format.html { redirect_to @zaklad, notice: 'Zaklad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zaklad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zaklads/1
  # DELETE /zaklads/1.json
  def destroy
    @zaklad = Zaklad.find(params[:id])
    @zaklad.destroy

    respond_to do |format|
      format.html { redirect_to zaklads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/zaklads_helper.rb
module ZakladsHelper
end

app/views/zaklads/_form.html.erb
<%= form_for(@zaklad) do |f| %>
  <% if @zaklad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zaklad.errors.count, "error") %> prohibited this zaklad from being saved:</h2>

      <ul>
      <% @zaklad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br />
    <%= f.datetime_select :data %>
  </div>
  <div class="field">
    <%= f.label :gospodarz %><br />
    <%= f.text_field :gospodarz %>
  </div>
  <div class="field">
    <%= f.label :gosc %><br />
    <%= f.text_field :gosc %>
  </div>
  <div class="field">
    <%= f.label :k1 %><br />
    <%= f.text_field :k1 %>
  </div>
  <div class="field">
    <%= f.label :k2 %><br />
    <%= f.text_field :k2 %>
  </div>
  <div class="field">
    <%= f.label :k3 %><br />
    <%= f.text_field :k3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zaklads/edit.html.erb
<h1>Editing zaklad</h1>

<%= render 'form' %>

<%= link_to 'Show', @zaklad %> |
<%= link_to 'Back', zaklads_path %>

app/views/zaklads/index.html.erb
<% if notice.class == "".class %>
    <div id="accept">
        <h1>ZAKŁAD ZOSTAŁ PRZYJĘTY!</h1>
    </div>
<% elsif notice.class == [].class %>
    <div id="fail">
        <h1>ZAKŁAD NIE ZOSTAŁ PRZYJĘTY!</h1>
        <ul>
        <% notice.each do |x| %>
            <li><%= x %></li>
        <% end %>
        </ul>
    </div>
<% end %>
<table border=1; width="100%">
    <thead>
        <td width="60%">Zakłady</td>
        <td width="40%">Wyniki</td>
    </thead>
    <tbody>
        <td valign="top">
            <% Event.active.each do |event| %>
                <% @i = 0 %>
                <% if event.zaklads.any? {|zaklad| zaklad.data > DateTime.now + 2.hours} %>
                    <h2><%= event.name %></h2>
                    <table>
                        <thead>
                            <tr>
                                <td>Data</td>
                                <td>Gospodarz</td>
                                <td>Gosc</td>
                                <td>1</td>
                                <td>X</td>
                                <td>2</td>
                                <td>Reputacja</td>
                                <td>Nick</td>
                                <td>Kod</td>
                                <td>Potwierdź</td>
                            </tr>
                        </thead>
                        <% event.zaklads.sort_by{|e| e.data}.each do |zaklad| %>
                            <% if zaklad.data < DateTime.now + 2.hours %>
                                <% kolor = "czerwony" %>
                            <% else %>
                                <% kolor = "zielony" %>
                                <% @i += 1 %>
                            <% end %>
                            <tbody>
                                <tr class=<%=kolor%>>
                                    <td><%=zaklad.data.strftime("%F %T")%></td>
                                    <td><%=zaklad.gospodarz%></td>
                                    <td><%=zaklad.gosc%></td>
                                        <%= form_tag(:controller => "obstawienies", :action => "create", :method => "post") do |f| %>
                                            <td><%= radio_button_tag "Reputacja", 1 %><%=zaklad.k1%></td>
                                            <% if zaklad.k2 == 0 %>
                                                <td class=off><%= radio_button_tag "Reputacja", 2, false, disabled: true %>-----</td>
                                            <% else %>
                                                <td><%= radio_button_tag "Reputacja", 2 %><%=zaklad.k2%></td>
                                            <% end %>
                                            <td><%= radio_button_tag "Reputacja", 3 %><%=zaklad.k3%></td>
                                            <td><%= text_field_tag "Ilosc", '', size: 5 %></td>
                                            <td><%= text_field_tag "Nick",'', size: 10 %><%= hidden_field_tag "Zaklad", zaklad.id %></td>
                                            <td><%= text_field_tag "Kod", '', size: 10 %></td>
                                            <% if kolor == "zielony" %>
                                                <td><%= submit_tag "Ok!" %></td>
                                            <% else %>
                                                <td><%= submit_tag "X", disabled: true %>
                                            <% end %>
                                        <% end %>
                                </tr>
                            </tbody>
                        <% end %>
                        <tfoot>
                            <tr>
                                <td colspan=3>Do kolejnego zakładu pozostało: <%=distance_of_time_in_words(event.zaklads.select { |x| x.data > DateTime.now + 2.hours }.sort_by{|x| x.data}.first.data, DateTime.now + 2.hours)%> </td>
                            </tr>
                        </tfoot>
                    </table>
                <% else %>
                    <% event.status = 1 %>
                    <% event.save %>
                <% end %>
            <% end %>
        </td>
        <td valign="top">
            <% Event.unactive.each do |event| %>
                <h2> <%= event.name %> </h2>
                <table width="100%">
                    <thead>
                        <td width="50%">Gospodarz</td>
                        <td width="50%">Gosc</td>
                    </thead>
                    <tbody>
                        <% event.zaklads.each do |zaklad| %>
                        <tr>
                            <% if zaklad.wynik == 1 %>
                                <td class="wygrany"><%= zaklad.gospodarz %></td>
                                <td class="przegrany"><%= zaklad.gosc %> </td>
                            <% elsif zaklad.wynik == 2 %>
                                <td class="remis"%><%= zaklad.gospodarz %></td>
                                <td class="remis"%><%= zaklad.gosc %></td>
                            <% else %>
                                <td class="przegrany"%><%= zaklad.gospodarz %></td>
                                <td class="wygrany"%><%= zaklad.gosc %></td>
                            <% end %>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
                <table border=1; rules='all', width="100%">
                    <thead>
                        <td width="33%">Nick</td>
                        <td width="33%">Zakład</td>
                        <td width="33%">Zdobycz/Strata</td>
                    </thead>
                    <tbody>
                        <% event.zaklads.each do |zaklad| %>
                            <% zaklad.obstawienies.each do |obstawienie| %>
                            <% if obstawienie.wygrana >= 0 %>
                                <tr class="zielony">
                            <% else %>
                                <tr class="czerwony">
                            <% end %>
                                <td><%= User.find(obstawienie.user_id).name %></td>
                                <% if obstawienie.opcja == 1 %>
                                    <td><%= zaklad.gospodarz %></td>
                                <% elsif obstawienie.opcja == 2 %>
                                    <td>Remis</td>
                                <% else %>
                                    <td><%= zaklad.gosc %></td>
                                <% end %>
                                <td><%= obstawienie.wygrana %></td>
                            </tr>
                            <% end %>
                        <% end %>
                    </tbody>
                </table>
            <% end %>
        </td>
    </tbody>
</table>

app/views/zaklads/new.html.erb
<h1>New zaklad</h1>

<%= render 'form' %>

<%= link_to 'Back', zaklads_path %>

app/views/zaklads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Data:</b>
  <%= @zaklad.data %>
</p>

<p>
  <b>Gospodarz:</b>
  <%= @zaklad.gospodarz %>
</p>

<p>
  <b>Gosc:</b>
  <%= @zaklad.gosc %>
</p>

<p>
  <b>K1:</b>
  <%= @zaklad.k1 %>
</p>

<p>
  <b>K2:</b>
  <%= @zaklad.k2 %>
</p>

<p>
  <b>K3:</b>
  <%= @zaklad.k3 %>
</p>


<%= link_to 'Edit', edit_zaklad_path(@zaklad) %> |
<%= link_to 'Back', zaklads_path %>