config/routes.rb
Zaklady::Application.routes.draw do
  
  root :to => 'zaklads#index'

  resources :obstawienies

  resources :zaklads

 

  get "zaklady/nowy"
  post "zaklady/nowy"

  get "zaklady/wynik"
  post "zaklady/wynik"

end

app/controllers/obstawienies_controller.rb
class ObstawieniesController < ApplicationController
  # GET /obstawienies
  # GET /obstawienies.json
  def index
    @obstawienies = Obstawienie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @obstawienies }
    end
  end

  # GET /obstawienies/1
  # GET /obstawienies/1.json
  def show
    @obstawieny = Obstawienie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @obstawieny }
    end
  end

  # GET /obstawienies/new
  # GET /obstawienies/new.json
  def new
    @obstawieny = Obstawienie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @obstawieny }
    end
  end

  # GET /obstawienies/1/edit
  def edit
    @obstawieny = Obstawienie.find(params[:id])
  end

  # POST /obstawienies
  # POST /obstawienies.json
  def create


    
    @user = User.where(name: params[:Nick]).first
    if @user
      @obstawieny = Obstawienie.new({:zaklad_id => params[:Zaklad], :user_id => @user.id, :opcja => params[:Reputacja], :reputacja => params[:Ilosc], :wygrana => 0})
    else
      @obstawieny = Obstawienie.new({:zaklad_id => params[:Zaklad], :user_id => 1, :opcja => params[:Reputacja], :reputacja => params[:Ilosc], :wygrana => 0})
    end
    respond_to do |format|
      if Zaklad.find(params[:Zaklad]).data  < DateTime.now + 2.hours
        format.html { redirect_to "/zaklads", notice: ["Obstawiono po terminie!","Nie oszukuj :)"] }
        format.json { render json: @obstawieny.errors, status: :unprocessable_entity }
      else        
        if not @user or @user.password != params[:Kod]
          format.html { redirect_to "/zaklads", notice: ["Błędny login lub kod"] }
          format.json { render json: @obstawieny.errors, status: :unprocessable_entity }
        else
          if @obstawieny.save
            format.html { redirect_to "/zaklads", notice: 'Zakład został postawiony!' }
            format.json { render json: @obstawieny, status: :created, location: @obstawieny }
          else
            format.html { redirect_to "/zaklads", notice: @obstawieny.errors.full_messages }
            format.json { render json: @obstawieny.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # PUT /obstawienies/1
  # PUT /obstawienies/1.json
  def update
    @obstawieny = Obstawienie.find(params[:id])

    respond_to do |format|
      if @obstawieny.update_attributes(params[:obstawieny])
        format.html { redirect_to @obstawieny, notice: 'Obstawienie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @obstawieny.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /obstawienies/1
  # DELETE /obstawienies/1.json
  def destroy
    @obstawieny = Obstawienie.find(params[:id])
    @obstawieny.destroy

    respond_to do |format|
      format.html { redirect_to obstawienies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/obstawienies_helper.rb
module ObstawieniesHelper
end

app/views/obstawienies/_form.html.erb
<%= form_for(@obstawieny) do |f| %>
  <% if @obstawieny.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@obstawieny.errors.count, "error") %> prohibited this obstawieny from being saved:</h2>

      <ul>
      <% @obstawieny.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zaklad_id %><br />
    <%= f.number_field :zaklad_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :opcja %><br />
    <%= f.number_field :opcja %>
  </div>
  <div class="field">
    <%= f.label :reputacja %><br />
    <%= f.number_field :reputacja %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/obstawienies/edit.html.erb
<h1>Editing obstawieny</h1>

<%= render 'form' %>

<%= link_to 'Show', @obstawieny %> |
<%= link_to 'Back', obstawienies_path %>

app/views/obstawienies/index.html.erb
<h1>Listing obstawienies</h1>

<table>
  <tr>
    <th>Zaklad</th>
    <th>User</th>
    <th>Opcja</th>
    <th>Reputacja</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @obstawienies.each do |obstawieny| %>
  <tr>
    <td><%= obstawieny.zaklad_id %></td>
    <td><%= obstawieny.user_id %></td>
    <td><%= obstawieny.opcja %></td>
    <td><%= obstawieny.reputacja %></td>
    <td><%= link_to 'Show', obstawieny %></td>
    <td><%= link_to 'Edit', edit_obstawieny_path(obstawieny) %></td>
    <td><%= link_to 'Destroy', obstawieny, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Obstawienie', new_obstawieny_path %>

app/views/obstawienies/new.html.erb
<h1>New obstawieny</h1>

<%= render 'form' %>

<%= link_to 'Back', obstawienies_path %>

app/views/obstawienies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Zaklad:</b>
  <%= @obstawieny.zaklad_id %>
</p>

<p>
  <b>User:</b>
  <%= @obstawieny.user_id %>
</p>

<p>
  <b>Opcja:</b>
  <%= @obstawieny.opcja %>
</p>

<p>
  <b>Reputacja:</b>
  <%= @obstawieny.reputacja %>
</p>


<%= link_to 'Edit', edit_obstawieny_path(@obstawieny) %> |
<%= link_to 'Back', obstawienies_path %>